# プロキシサーバーのブロックリスト設定
# 最終更新: 2025-01-13

# ブロックするIPアドレスのリスト
blocked_ips:
  - 192.168.1.100  # 開発環境
  - 10.0.0.50      # テスト環境
  - 172.16.0.100   # ステージング環境

# ブロックするドメインのリスト
blocked_domains:
  - example.com             # テストドメイン
  - "*.badsite.com"        # 不正なサイト
  - "*.malicious.org"      # マルウ